"use client";
import { FormEvent, useEffect, useState } from "react";

type Category = { id: string; name: string };
type Product = { id: string; name: string; slug: string; price: string; isActive: boolean; category: Category };

export default function ProductsAdmin() {
  const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/admin/products").then((r) => r.json()).then(setProducts); fetch("/api/admin/categories").then((r) => r.json()).then(setCategories); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const body = { name: form.get("name"), description: form.get("description"), price: form.get("price"), categoryId: form.get("categoryId"), sizes: String(form.get("sizes") || "").split(",").map((x) => x.trim()).filter(Boolean), colors: String(form.get("colors") || "").split(",").map((x) => x.trim()).filter(Boolean), printPositions: String(form.get("printPositions") || "").split(",").map((x) => x.trim()).filter(Boolean), isCustomizable: form.get("isCustomizable") === "on", isFeatured: form.get("isFeatured") === "on", isActive: true }; const response = await fetch("/api/admin/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setMessage(response.ok ? "Product created." : (await response.json()).error); if (response.ok) { event.currentTarget.reset(); const fresh = await fetch("/api/admin/products").then((r) => r.json()); setProducts(fresh); } }
  return <><p className="eyebrow">Catalogue / Products</p><h1 className="mt-2 text-3xl">Products</h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="card overflow-hidden"><div className="border-b border-line p-4 font-medium">Current catalogue</div>{products.length ? products.map((product) => <div className="flex items-center justify-between border-b border-line p-4" key={product.id}><div><p className="font-medium">{product.name}</p><p className="text-sm text-neutral-500">{product.category.name} · PKR {String(product.price)}</p></div><span className="text-xs">{product.isActive ? "Active" : "Archived"}</span></div>) : <p className="p-5 text-sm text-neutral-600">No products yet.</p>}</div><form onSubmit={submit} className="card p-5"><h2 className="text-xl">Add product</h2>{["name","description","price","sizes","colors","printPositions"].map((name) => <label className="mt-4 block text-sm" key={name}>{name === "description" ? "Description" : name === "printPositions" ? "Print positions (comma separated)" : name[0].toUpperCase() + name.slice(1)}{name === "description" ? <textarea name={name} className="field mt-1" rows={4} required /> : <input name={name} className="field mt-1" type={name === "price" ? "number" : "text"} required={!["sizes","colors","printPositions"].includes(name)} />}</label>)}<label className="mt-4 block text-sm">Category<select name="categoryId" className="field mt-1" required>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label className="mt-4 flex gap-2 text-sm"><input name="isCustomizable" type="checkbox" defaultChecked /> Customizable</label><label className="mt-2 flex gap-2 text-sm"><input name="isFeatured" type="checkbox" /> Featured</label>{message && <p className="mt-4 text-sm">{message}</p>}<button className="button button-clay mt-5 w-full">Create product</button></form></div></>;
}
