"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ProductImageManager } from "@/components/product-image-manager";
const list = (value: FormDataEntryValue | null) => String(value || "").split(",").map((x) => x.trim()).filter(Boolean);
type Category = { id: string; name: string }; type Product = { id: string; name: string; price: string; isActive: boolean; category: Category };
export default function ProductsAdmin() { const [products, setProducts] = useState<Product[]>([]), [categories, setCategories] = useState<Category[]>([]), [message, setMessage] = useState(""), [imageIds, setImageIds] = useState<string[]>([]); const load = () => { fetch("/api/admin/products").then((r) => r.json()).then(setProducts); fetch("/api/admin/categories").then((r) => r.json()).then(setCategories); }; useEffect(load, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const response = await fetch("/api/admin/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: f.get("name"), description: f.get("description"), fullDescription: f.get("fullDescription"), price: f.get("price"), categoryId: f.get("categoryId"), sizes: list(f.get("sizes")), colors: list(f.get("colors")), printPositions: list(f.get("printPositions")), tags: list(f.get("tags")), imageIds, isCustomizable: f.get("isCustomizable") === "on", isFeatured: f.get("isFeatured") === "on", isNew: f.get("isNew") === "on", isActive: true }) }); setMessage(response.ok ? "Product created." : (await response.json()).error || "Could not create product."); if (response.ok) { event.currentTarget.reset(); setImageIds([]); load(); } }
  return <><p className="eyebrow">Catalogue / Products</p><h1 className="mt-2 text-3xl">Products</h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="card overflow-hidden"><div className="border-b border-line p-4 font-medium">Current catalogue</div>{products.length ? products.map((product) => <div className="flex items-center justify-between border-b border-line p-4" key={product.id}><div><p className="font-medium">{product.name}</p><p className="text-sm text-neutral-500">{product.category.name} · PKR {String(product.price)}</p></div><div className="flex items-center gap-3"><span className="text-xs">{product.isActive ? "Active" : "Archived"}</span><Link className="text-xs underline" href={`/admin/products/${product.id}`}>Edit</Link></div></div>) : <p className="p-5 text-sm text-neutral-600">No products yet.</p>}</div><form onSubmit={submit} className="card p-5"><h2 className="text-xl">Add product</h2>{["name", "description", "fullDescription", "price", "sizes", "colors", "printPositions", "tags"].map((name) => <label className="mt-4 block text-sm" key={name}>{name === "fullDescription" ? "Full description" : name === "printPositions" ? "Print positions (comma separated)" : name === "tags" ? "Tags (comma separated)" : name[0].toUpperCase() + name.slice(1)}{["description", "fullDescription"].includes(name) ? <textarea name={name} className="field mt-1" rows={name === "fullDescription" ? 5 : 3} required={name === "description"} /> : <input name={name} className="field mt-1" type={name === "price" ? "number" : "text"} required={!['sizes', 'colors', 'printPositions', 'tags'].includes(name)} />}</label>)}<label className="mt-4 block text-sm">Category<select name="categoryId" className="field mt-1" required>{categories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><ProductImageManager onChange={setImageIds}/><label className="mt-4 flex gap-2 text-sm"><input name="isCustomizable" type="checkbox" defaultChecked /> Customizable</label><label className="mt-2 flex gap-2 text-sm"><input name="isFeatured" type="checkbox" /> Featured</label><label className="mt-2 flex gap-2 text-sm"><input name="isNew" type="checkbox" /> New</label>{message && <p className="mt-4 text-sm">{message}</p>}<button className="button button-clay mt-5 w-full">Create product</button></form></div></>; }
