import Image from "next/image";
import Link from "next/link";
import { demoCategories, featuredDemoProducts, newDemoProducts } from "@/lib/demo";
import { ProductCard } from "@/components/product-card";

export default function Home() { return <>
  <section className="wrap grid min-h-[570px] items-stretch gap-8 py-8 md:grid-cols-[1fr_.9fr] md:py-14"><div className="flex flex-col justify-center py-8"><p className="eyebrow">NAQSH / Custom print studio</p><h1 className="mt-5 max-w-xl text-5xl leading-[.95] font-semibold tracking-tight md:text-7xl">Where ideas<br />take form.</h1><p className="mt-6 max-w-md text-lg leading-8 text-neutral-600">Custom printed pieces for the things you want to wear, carry, share and remember.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button button-clay" href="/shop">Shop products</Link><Link className="button" href="/custom-design">Create your design</Link></div></div><div className="relative min-h-90 overflow-hidden bg-line"><Image priority src="https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1100&q=85" alt="Creative apparel detail" fill className="object-cover" sizes="(max-width:768px) 100vw,50vw" /></div></section>
  <section className="border-y border-line bg-white/40 py-16"><div className="wrap"><p className="eyebrow">What can we make?</p><h2 className="mt-2 max-w-xl text-3xl">Starting points for your next idea.</h2><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{title:"Wear",copy:"Tees, oversized fits, hoodies and sweatshirts.",href:"/category/everyday-tees"},{title:"Carry",copy:"Totes and bags made for everyday use.",href:"/category/tote-bags"},{title:"Gifts & Objects",copy:"Mugs, prints, stickers and more.",href:"/category/mugs"},{title:"Custom",copy:"Have something else in mind? Bring it to us.",href:"/custom-design"}].map((item,index)=><Link key={item.title} href={item.href} className="card p-6 transition hover:border-ink"><span className="text-clay">0{index+1}</span><h3 className="mt-8 text-xl">{item.title}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{item.copy}</p></Link>)}</div></div></section>
  <section className="wrap py-16"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Shop by category</p><h2 className="mt-2 text-3xl">Find your canvas</h2></div><Link className="text-sm underline" href="/shop">View all products</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{demoCategories.slice(0,10).map(category=><Link href={`/category/${category.slug}`} key={category.slug} className="group relative aspect-[4/5] overflow-hidden bg-line"><Image src={category.image} alt={category.name} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(max-width:640px) 50vw,20vw"/><div className="absolute inset-x-0 bottom-0 bg-black/50 p-4 text-white"><p className="text-xs text-white/80">{category.group}</p><h3 className="mt-1">{category.name}</h3></div></Link>)}</div></section>
  <section className="border-y border-line bg-white/40 py-16"><div className="wrap"><div className="flex items-end justify-between"><div><p className="eyebrow">Featured pieces</p><h2 className="mt-2 text-3xl">Made to become yours</h2></div><Link className="text-sm underline" href="/shop">Shop all</Link></div><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{featuredDemoProducts.map(product=><ProductCard product={product} key={product.id}/>)}</div></div></section>
  <section className="wrap grid gap-8 py-16 md:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-90 overflow-hidden bg-line"><Image src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1100&q=85" alt="Creative studio work in progress" fill className="object-cover" sizes="(max-width:768px) 100vw,50vw"/></div><div className="flex flex-col justify-center"><p className="eyebrow">Have something in mind?</p><h2 className="mt-3 max-w-lg text-4xl leading-tight">Bring a reference, a sketch, artwork or just a feeling.</h2><p className="mt-5 max-w-lg leading-7 text-neutral-600">We’ll help turn it into something you can wear, carry or gift — from a one-off piece to a small run for your people.</p><Link href="/custom-design" className="button button-clay mt-7 w-fit">Create your design</Link></div></section>
  <section className="bg-ink py-16 text-paper"><div className="wrap"><p className="eyebrow text-[#b7c5b5]">Made for more than one moment</p><h2 className="mt-3 max-w-xl text-4xl">A good idea can become a keepsake, a uniform or a whole memory.</h2><div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-5">{[["For yourself","A piece made around your idea."],["For friends","Matching tees, gifts and memories."],["For events","Custom pieces for birthdays, trips and celebrations."],["For brands","Small-batch merchandise and branded pieces."],["For teams","Apparel for clubs, teams and communities."]].map(([title,copy])=><div key={title}><h3 className="text-lg">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-300">{copy}</p></div>)}</div></div></section>
  <section className="wrap py-16"><div className="flex items-end justify-between"><div><p className="eyebrow">New from the studio</p><h2 className="mt-2 text-3xl">Fresh surfaces for fresh ideas</h2></div><Link className="text-sm underline" href="/shop">Browse the studio</Link></div><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{newDemoProducts.map(product=><ProductCard product={product} key={product.id}/>)}</div></section>
  <section className="border-y border-line bg-white/40 py-16"><div className="wrap grid gap-8 md:grid-cols-2"><div><p className="eyebrow">Made with intention</p><h2 className="mt-3 text-4xl leading-tight">Small details make a piece worth keeping.</h2></div><div className="grid gap-6 sm:grid-cols-2">{[["Thoughtful printing","We focus on clean, durable results."],["Made to order","Your piece is prepared specifically for you."],["Small orders welcome","You don’t need a warehouse-sized order to bring an idea to life."],["Based in Lahore","Designed and produced locally."]].map(([title,copy])=><div key={title}><h3 className="font-medium">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{copy}</p></div>)}</div></div></section>
  <section className="wrap py-16"><p className="eyebrow">How it works</p><div className="mt-5 grid gap-8 md:grid-cols-3">{[["1","Share your idea","Choose a starting product or tell us what you have in mind."],["2","Confirm the details","We’ll discuss size, print, quantity and final price on WhatsApp."],["3","Made with care","Once confirmed, your piece moves into production."]].map(([number,title,copy])=><div key={number}><span className="text-clay">{number}</span><h3 className="mt-2 text-xl">{title}</h3><p className="mt-2 text-sm leading-6 text-neutral-600">{copy}</p></div>)}</div></section>
</>; }
