import Image from "next/image";
import Link from "next/link";
import { demoCategories, featuredDemoProducts } from "@/lib/demo";
import { homeContent } from "@/lib/site-content";
import { ProductCard } from "@/components/product-card";

export default function Home() {
  const { hero, custom, story, howItWorks, finalCta } = homeContent;
  return <>
    <section className="bg-sand"><div className="wrap grid min-h-[720px] lg:grid-cols-[.84fr_1.16fr]"><div className="relative z-1 flex flex-col justify-center py-20 lg:py-28"><p className="eyebrow text-clay">NAQSH / Lahore</p><p className="mt-8 text-xs font-bold uppercase tracking-[.25em]">{hero.eyebrow}</p><h1 className="display mt-5 max-w-2xl text-7xl leading-[.76] sm:text-8xl lg:text-[9.5rem]">NAQSH<br/><span className="text-clay">Where Ideas</span><br/>Take Form.</h1><p className="mt-9 max-w-md text-lg leading-8 text-[#4d453c]">{hero.text}</p><div className="mt-10 flex flex-wrap gap-4"><Link className="button button-clay" href="/shop">Explore Collection</Link><Link className="button" href="/custom-design">Create Your Own</Link></div></div><div className="relative min-h-[470px] lg:my-10 lg:min-h-0"><div className="absolute -left-5 top-8 h-32 w-32 bg-clay sm:h-48 sm:w-48"/><div className="absolute inset-y-0 right-0 w-[93%] overflow-hidden"><Image priority src={hero.image} alt="NAQSH creative apparel" fill className="object-cover" sizes="(max-width:1024px) 100vw,60vw"/></div><p className="absolute bottom-7 left-0 max-w-36 text-xs leading-5 uppercase tracking-[.14em] text-ink">Objects, apparel and ideas made personal.</p></div></div></section>

    <section className="wrap py-24 lg:py-32"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Explore categories</p><h2 className="display mt-5 text-5xl leading-[.84] sm:text-6xl">A surface for every kind of idea.</h2></div><p className="max-w-lg self-end text-lg leading-8 text-[#5c5349]">From everyday essentials to pieces made for gifting, the collection begins with a material and ends with your point of view.</p></div><div className="mt-16 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{demoCategories.slice(0,4).map((category,index) => <Link href={`/category/${category.slug}`} key={category.slug} className={`group block ${index===0?"lg:mt-16":""}`}><div className="relative aspect-[3/4] overflow-hidden bg-sand"><Image src={category.image} alt={category.name} fill className="image-lift object-cover" sizes="(max-width:640px) 50vw,25vw"/></div><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-clay">0{index+1} / {category.group}</p><h3 className="display mt-2 text-3xl leading-none">{category.name}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#665d52]">{category.description}</p></Link>)}</div><Link className="button mt-12" href="/shop">View full collection</Link></section>

    <section className="bg-ink py-24 text-paper lg:py-32"><div className="wrap"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow text-[#d1b8a5]">Selected by NAQSH</p><h2 className="display mt-5 text-5xl leading-[.84] sm:text-6xl">Made to become yours.</h2></div><Link className="text-xs font-bold uppercase tracking-[.16em] text-[#e5c6b1] underline underline-offset-6" href="/shop">Shop all pieces →</Link></div><div className="mt-16 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{featuredDemoProducts.slice(0,4).map(product => <ProductCard product={product} key={product.id}/>)}</div></div></section>

    <section className="bg-sand py-8 lg:py-16"><div className="wrap grid lg:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-[470px] overflow-hidden"><Image src={custom.image} alt="Creative work in progress" fill className="object-cover" sizes="(max-width:1024px) 100vw,55vw"/></div><div className="flex flex-col justify-center bg-ink px-8 py-16 text-paper sm:px-14 lg:px-20"><p className="eyebrow text-[#d1b8a5]">{custom.eyebrow}</p><h2 className="display mt-6 max-w-md text-5xl leading-[.82] sm:text-6xl">Your idea.<br/>Your design.<br/><span className="text-[#d78d70]">Your NAQSH.</span></h2><p className="mt-8 max-w-md leading-7 text-stone-300">{custom.text}</p><Link href="/custom-design" className="button button-clay mt-10 w-fit">Create Your Own</Link></div></div></section>

    <section className="wrap py-28 lg:py-36"><p className="eyebrow">How NAQSH works</p><div className="mt-5 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><h2 className="display text-5xl leading-[.84] sm:text-6xl">A simple route from thought to thing.</h2><div className="grid gap-x-8 gap-y-10 sm:grid-cols-2">{howItWorks.map(([number,title,text])=><div key={number} className="border-t border-ink pt-4"><span className="text-sm font-bold tracking-widest text-clay">{number}</span><h3 className="mt-8 text-lg font-bold uppercase tracking-[.08em]">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-[#665d52]">{text}</p></div>)}</div></div></section>

    <section className="border-y border-line bg-[#fbfaf7]"><div className="wrap grid min-h-[460px] items-center gap-10 py-20 lg:grid-cols-[1.1fr_.9fr]"><h2 className="display max-w-3xl text-6xl leading-[.78] sm:text-7xl lg:text-8xl">Ideas are everywhere.<br/><span className="text-clay">NAQSH gives them a form.</span></h2><div><p className="text-lg leading-8 text-[#5c5349]">{story.text}</p><Link className="mt-8 inline-block text-xs font-bold uppercase tracking-[.16em] text-clay underline underline-offset-6" href="/about">Read our story →</Link></div></div></section>

    <section className="bg-clay py-24 text-white lg:py-32"><div className="wrap"><p className="text-xs font-bold uppercase tracking-[.2em] text-white/75">Make something personal</p><h2 className="display mt-7 text-6xl leading-[.76] sm:text-7xl lg:text-8xl">{finalCta.title}<br/>{finalCta.text}</h2><Link href="/custom-design" className="button mt-12 border-white text-white hover:bg-white hover:text-clay">Start Creating</Link></div></section>
  </>;
}
