"use client";
import { FormEvent, useEffect, useState } from "react";
import { ProductImageManager } from "@/components/product-image-manager";
const list = (value: FormDataEntryValue | null) => String(value || "").split(",").map((x) => x.trim()).filter(Boolean);
export function EditProductClient({ id }: { id: string }) {
  const [product, setProduct] = useState<any>(null), [categories, setCategories] = useState<any[]>([]), [message, setMessage] = useState(""), [imageIds, setImageIds] = useState<string[]>([]);
  useEffect(() => { fetch(`/api/admin/products/${id}`).then((r) => r.json()).then((item) => { setProduct(item); setImageIds(item.images?.map((image: any) => image.mediaId || image.id) || []); }); fetch("/api/admin/categories").then((r) => r.json()).then(setCategories); }, [id]);
  if (!product) return <p>Loading product...</p>;
  const variant = product.variants?.[0];
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); const response = await fetch(`/api/admin/products/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: f.get("name"), slug: f.get("slug"), description: f.get("description"), fullDescription: f.get("fullDescription"), price: f.get("price"), categoryId: f.get("categoryId"), sizes: list(f.get("sizes")), colors: list(f.get("colors")), printPositions: list(f.get("printPositions")), tags: list(f.get("tags")), imageIds, isCustomizable: f.get("isCustomizable") === "on", isFeatured: f.get("isFeatured") === "on", isNew: f.get("isNew") === "on", isActive: f.get("isActive") === "on" }) }); setMessage(response.ok ? "Saved." : "Could not save."); }
  async function archive() { await fetch(`/api/admin/products/${id}`, { method: "DELETE" }); setMessage("Product archived."); }
  const fields = [["name", "Name", product.name], ["slug", "Slug", product.slug], ["price", "Price", product.price], ["sizes", "Sizes", variant?.sizes?.join(", ")], ["colors", "Colors", variant?.colors?.join(", ")], ["printPositions", "Print positions", variant?.printPositions?.join(", ")], ["tags", "Tags", product.tags?.join(", ")]];
  return <><p className="eyebrow">Catalogue / Edit product</p><h1 className="mt-2 text-3xl">{product.name}</h1><form onSubmit={save} className="card mt-8 max-w-2xl p-6">{fields.map(([name, label, value]) => <label className="mt-4 block text-sm" key={name}>{label}<input className="field mt-1" name={name} defaultValue={String(value || "")} required={!['sizes', 'colors', 'printPositions', 'tags'].includes(name)} /></label>)}<label className="mt-4 block text-sm">Description<textarea className="field mt-1" name="description" defaultValue={product.description} rows={3} required /></label><label className="mt-4 block text-sm">Full description<textarea className="field mt-1" name="fullDescription" defaultValue={product.fullDescription || ""} rows={6} /></label><label className="mt-4 block text-sm">Category<select className="field mt-1" name="categoryId" defaultValue={product.categoryId}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><ProductImageManager initial={product.images} onChange={setImageIds}/>{[["isCustomizable", "Customizable", product.isCustomizable], ["isFeatured", "Featured", product.isFeatured], ["isNew", "New", product.isNew], ["isActive", "Active", product.isActive]].map(([name, label, checked]) => <label className="mt-3 flex gap-2 text-sm" key={name}><input type="checkbox" name={name} defaultChecked={Boolean(checked)} /> {label}</label>)}{message && <p className="mt-4 text-sm">{message}</p>}<div className="mt-6 flex gap-3"><button className="button button-clay">Save changes</button><button type="button" className="button" onClick={archive}>Archive</button></div></form></>;
}
