"use client";
import { FormEvent, useEffect, useState } from "react";
type Item = { id: string; name: string; slug: string; description?: string; imageId?: string; isVisible: boolean; position: number };
export default function Categories() { const [items, setItems] = useState<Item[]>([]), [message, setMessage] = useState(""); const load = () => fetch("/api/admin/categories").then((r) => r.json()).then(setItems); useEffect(() => { void load(); }, []);
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await fetch("/api/admin/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(f)) }); setMessage(r.ok ? "Category created." : "Could not create category."); if (r.ok) { e.currentTarget.reset(); load(); } }
  async function change(item: Item, data: object) { const r = await fetch(`/api/admin/categories/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); setMessage(r.ok ? "Category updated." : "Could not update category."); load(); }
  async function edit(item: Item) { const name = prompt("Category name", item.name); if (!name) return; const slug = prompt("Slug", item.slug); if (!slug) return; const description = prompt("Description", item.description || ""); const imageId = prompt("Category image Media ID (leave blank to remove)", item.imageId || ""); await change(item, { name, slug, description, imageId }); }
  async function move(index: number, dir: number) { const next = [...items], to = index + dir; if (to < 0 || to >= next.length) return; [next[index], next[to]] = [next[to], next[index]]; setItems(next); await fetch("/api/admin/categories", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ids: next.map((x) => x.id) }) }); }
  return <><p className="eyebrow">Catalogue</p><h1 className="mt-2 text-3xl">Categories</h1><p className="mt-2 text-sm text-neutral-600">For an image, upload it in Media Library and paste its Media ID when editing.</p><div className="mt-8 grid gap-8 md:grid-cols-[1fr_320px]"><div className="card">{items.map((item, i) => <div className="flex items-center gap-3 border-b border-line p-4" key={item.id}><div className="min-w-0 flex-1"><p className="font-medium">{item.name}</p><p className="text-xs text-neutral-500">/{item.slug} · {item.description || "No description"}</p></div><button className="button !p-2" onClick={() => move(i, -1)} aria-label="Move up">↑</button><button className="button !p-2" onClick={() => move(i, 1)} aria-label="Move down">↓</button><button className="text-xs underline" onClick={() => edit(item)}>Edit</button><button className="text-xs underline" onClick={() => change(item, { isVisible: !item.isVisible })}>{item.isVisible ? "Hide" : "Show"}</button><button className="text-xs text-clay underline" onClick={async () => { if (confirm(`Delete ${item.name}?`)) { const r = await fetch(`/api/admin/categories/${item.id}`, { method: "DELETE" }); setMessage(r.ok ? "Category deleted." : "Cannot delete a category with products."); load(); } }}>Delete</button></div>)}</div><form onSubmit={create} className="card p-5"><h2 className="text-xl">Add category</h2><label className="mt-4 block text-sm">Name<input className="field mt-1" name="name" required /></label><label className="mt-4 block text-sm">Slug (optional)<input className="field mt-1" name="slug" /></label><label className="mt-4 block text-sm">Description<input className="field mt-1" name="description" /></label>{message && <p className="mt-3 text-sm">{message}</p>}<button className="button button-clay mt-5">Create category</button></form></div></>; }
